#!/bin/bash
#-------------------------------------------------------
# Bash-script autogenerated by im4java
# at Mon Jan 11 14:35:30 CST 2016
#-------------------------------------------------------

convert \
   \
  -auto-orient "/Users/fei/Desktop/IMG/tian_1.png" "/Users/fei/Desktop/IMG/tian_1_1.png"

